version: '3'
tasks:
  default:
    cmds:
      - task --list-all
  ci:
    cmds:
      - docker compose --profile=fullstack up -d
  system_deps:
    run: once
    cmds:
      - sudo apt update && sudo apt upgrade -y
      - sudo apt install wget curl git btop python3-rpi.gpio npm -y
      - sudo npm install -g @go-task/cli
  install_pyenv:
    deps:
      - system_deps
    cmds:
      - curl -fsSL https://pyenv.run | bash
      - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      - echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
      - echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
  install_poetry:
    deps:
      - system_deps
    cmds:
      - curl -sSL https://install.python-poetry.org | python3 -
      - echo 'export PATH="/home/thermalplant/.local/bin:$PATH"' >> ~/.bashrc
  install_docker:
    deps:
      - system_deps
    cmds:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sudo sh get-docker.sh
      - sudo apt-get install docker-compose-plugin
      - sudo service docker start
  deploy_full_stack:
    cmds:
      - docker compose --profile=fullstack up -d