global:
  scrape_interval: 1s  # Default scrape interval for metrics

scrape_configs:
  - job_name: "node_exporter"  # Job name for Node Exporter
    static_configs:
      - targets: ["localhost:9100"]