global:
  scrape_interval: 1s # Default scrape interval for metrics
  external_labels:
    monitor: 'thermalplant'
scrape_configs:
- job_name: "node_exporter" # Job name for Node Exporter
  static_configs:
  - targets: [ "localhost:9100" ]
- job_name: 'cadvisor'
  static_configs:
  - targets: [ "localhost:8080" ]
- job_name: postgres
  static_configs:
  - targets: [ "localhost:9187" ]
